name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag areskiko/ababot:$(date +%s)
      
      
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Publish the Docker image
        run: docker push areskiko/ababot
